---
title: "Laboratorio 1 - Analisi predittiva"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("C:/Users/PayThePizzo/Projects/PredictiveAnalysisNotes/Labs/lab01")
```

```{r}
pengs <- read.csv("penguins.csv")
pengs <- na.omit(pengs) ## same dataset without missing values
```


```{r}

x <- pengs$body_mass_g
y <- pengs$flipper_length_mm
n <- length(x)

s2x <- sum((x-mean(x))^2)/n
s2y <- sum((y-mean(y))^2)/n

covxy <- cov(x,y) 
rxy <- cor(x,y)

mx <- mean(x)
<- mean(y)

beta1 <- rxy * sqrt(s2y/s2x)
beta0 <- my - beta1 *mx

#plot (target ~ predictor, data = df)
plot(flipper_length_mm ~ body_mass_g, data = pengs,pch = 16)

#Aggiunge retta bo+b1x
abline(beta0, beta1, col = 2, lwd = 1.4)

yhat <- beta0 +  beta1 * x # valori stimati 

sum((y-yhat)^2) ## empirical MSE 
sum((y-(137+0.016*x))^2) 

```

In realtà si userà sempre la funzione `lm`

```{r}

#lm(target ~ predittori, data = dataset)

fit <- lm(flipper_length_mm ~ body_mass_g, data = pengs)
fit
class(fit)
coef(fit)
summary(fit)
(se <- sqrt(sum((yhat - y)^2)/(n-2)))
head(fitted(fit),10)
head(yhat, 10)
head(residuals(fit), 10)
head((y - yhat), 10)
sqrt(sum(residuals(fit)^2)/(n-2))
sqrt(sum(fit$residuals^2)/(fit$df.residual))
```


Abbiamo verificato come R calcola le stime di $\beta_0$ e $\beta_1$, vediamo ora da dove arriva la stima dell'incertezza: 

```{r}
summary(fit)$coefficients[,2]
se/sqrt(n*s2x)
se * sqrt(1/n + mx^2/(n*s2x))
```

Cosa succede se cambiamo le scale in cui misuriamo le variabile. 

```{r}
fit <- lm(flipper_length_mm ~ body_mass_g, data = pengs)
# abline(coef(fit), col = 4)
```

```{r}
head(fitted(fit))
head(predict(fit))
pred1 <- predict(fit, se.fit = TRUE)
## from slides 
varmx <- (se^2/n) * (1+(x-mx)^2/s2x)
plot(pengs$body_mass_g, pred1$se.fit, pch = 16, cex = 1.2)
points(pengs$body_mass_g, sqrt(varmx), col = 2, pch = 16)
nd <- data.frame(body_mass_g=c(2000, 3000, 8000), 
                 pippo = c(2000, 3000, 8000))
pred2 <- predict(fit, newdata = nd, se.fit = TRUE)

plot(flipper_length_mm ~ body_mass_g, data = pengs, pch = 16, col = "grey60", xlim = c(2000, 9000), ylim = range(pred2$fit))
points(nd$body_mass_g, pred2$fit, col = "dodgerblue", pch = 4, cex = 1.9, lwd = 3)
abline(coef(fit), col = 2)
coef(fit)
# come interpretare l'intercetta  
predict(fit, newdata =  data.frame(body_mass_g=0))
# come interpretare il coef angolare 
predict(fit, newdata =  data.frame(body_mass_g=4001)) - 
  predict(fit, newdata =  data.frame(body_mass_g=4000))
```


# Simulazione come metodo per verificare la teoria 

Il modello teorico: 

\[Y=\beta_0 + \beta_1 X + \varepsilon\]

$\varepsilon$ iid, omoschedastici a media 0

```{r}
n <- 30
x <- seq(0, 1, length.out = n)
b0 <- 1; b1 <- 2
error <- rexp(n, 1)-1
y <- b0 + b1 * x+ error 
plot(x,y)
coef(lm(y~x))
out <- coef(lm(y~x))
set.seed(586328)
for(j in 1:1000){
  error <- rexp(n, 1)-1
  y <- b0 + b1 * x+ error 
  out <- rbind(out, coef(lm(y~x)))
}
hist(out[,1]); mean(out[,1])
hist(out[,2]); abline(v = b1, col = 2) ; mean(out[,2])
sd(out[,1])
sd(out[,2])
```




